description: Learning Rate Sweep for Pytorch Mnist Competition

# Training script to run
program: pytorch_kmnist.py  

# Method can be bayes, random, grid
method: bayes

# Metric to optimize
metric:
  name: kmnist_val_acc
  goal: minimize

# Should we early terminate runs
early_terminate:
  type: envelope

# Parameters to search over
parameters:
  learning_rate_start:
    min: 0.001
    max: 0.05
  learning_rate_decay:
    min: 0.8
    max: 1
  dropout:
    min: 0.4
    max: 0.6
